version: "3.9"

services:

  mongodb:

    image: mongo:8

    container_name: aihub-mongo

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: aihub

    volumes:
      - mongodb_data:/data/db

volumes:

  mongodb_data: